# Shapes and slices of nD arrays

In [1]:
import numpy as np

In [2]:
n_rows = 4
n_cols = 5

In [3]:
a = np.arange(n_rows*n_cols)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
b = a.reshape(n_rows, n_cols)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
b.shape

(4, 5)

What are the values in the first column?

In [5]:
b[:,0]

array([ 0,  5, 10, 15])

What are the values in the first row?

In [6]:
b[0,:]

array([0, 1, 2, 3, 4])

Can we make a 3D array?

In [7]:
nx = 4
ny = 3
nz = 2

In [8]:
c = np.arange(nx*ny*nz)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [12]:
c.shape

(24,)

In [9]:
d = c.reshape(nz, ny, nx)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [11]:
d.shape

(2, 3, 4)